source 'https://rubygems.org'
ruby '2.3.3'

gem 'rake'
gem 'sinatra'
gem 'grape'
gem 'grape-swagger'
gem 'rack-cors'
gem 'activesupport', :require => 'active_support/core_ext/hash/conversions'

# gem 'htmlentities'
# gem 'nokogiri'
# gem 'json'
# gem 'faker'
# gem 'grape-entity'